# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Full Court Press 
email: bheinig@gmail.com
description: "Welcome to Full Court Press, where we dive head first into the analytic underpinnings of basketball" 
baseurl:
url: "https://brady-heinig.github.io" #  change this to "https://<your-github-username>.github.io"
image: /assets/images/shai.png
author: Brady Heinig
copyright: BMH # Your initials or what you want the copyright to be.  Leave empty for no copyright
footer_description:

# Social media users names.  Leave fields blank that you don't want displayed
twitter_username: 
github_username:  brady-heinig
linkedin_username: Brady Heinig
dribbble_username: 
facebook_username: Brady Heinig
flickr_username:
instagram_username: bradyheinig_
pinterest_username:
youtube_username: 
googleplus_username:

plugins:
  - jekyll-feed

