# Site settings
title: Hi, I'm Brady
description: Brady Heinig's professional portfolio site
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Brady Heinig
user_title:
user_job_title: Data Scientist
email: bmheinig [at] gmail.com
twitter_username: 
github_username:  brady-heinig

exclude: ['package.json', 'src' , 'node_modules']
collections:
  pages:
    output: true
    permalink: /:path/
